// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: cluster/events.proto

package cluster

import (
	common "eddisonso.com/cluster-monitor/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.EventMetadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Nodes         []*NodeMetrics         `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetrics) Reset() {
	*x = ClusterMetrics{}
	mi := &file_cluster_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetrics) ProtoMessage() {}

func (x *ClusterMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetrics.ProtoReflect.Descriptor instead.
func (*ClusterMetrics) Descriptor() ([]byte, []int) {
	return file_cluster_events_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterMetrics) GetMetadata() *common.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClusterMetrics) GetNodes() []*NodeMetrics {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,4,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	Conditions    []*NodeCondition       `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_cluster_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_cluster_events_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *NodeMetrics) GetConditions() []*NodeCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type NodeCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCondition) Reset() {
	*x = NodeCondition{}
	mi := &file_cluster_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCondition) ProtoMessage() {}

func (x *NodeCondition) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCondition.ProtoReflect.Descriptor instead.
func (*NodeCondition) Descriptor() ([]byte, []int) {
	return file_cluster_events_proto_rawDescGZIP(), []int{2}
}

func (x *NodeCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PodStatusSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.EventMetadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Pods          []*PodStatus           `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatusSnapshot) Reset() {
	*x = PodStatusSnapshot{}
	mi := &file_cluster_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatusSnapshot) ProtoMessage() {}

func (x *PodStatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatusSnapshot.ProtoReflect.Descriptor instead.
func (*PodStatusSnapshot) Descriptor() ([]byte, []int) {
	return file_cluster_events_proto_rawDescGZIP(), []int{3}
}

func (x *PodStatusSnapshot) GetMetadata() *common.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PodStatusSnapshot) GetPods() []*PodStatus {
	if x != nil {
		return x.Pods
	}
	return nil
}

type PodStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RestartCount  int32                  `protobuf:"varint,3,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	OomKilled     bool                   `protobuf:"varint,4,opt,name=oom_killed,json=oomKilled,proto3" json:"oom_killed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_cluster_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_cluster_events_proto_rawDescGZIP(), []int{4}
}

func (x *PodStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *PodStatus) GetOomKilled() bool {
	if x != nil {
		return x.OomKilled
	}
	return false
}

var File_cluster_events_proto protoreflect.FileDescriptor

const file_cluster_events_proto_rawDesc = "" +
	"\n" +
	"\x14cluster/events.proto\x12\acluster\x1a\x12common/types.proto\"o\n" +
	"\x0eClusterMetrics\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.common.EventMetadataR\bmetadata\x12*\n" +
	"\x05nodes\x18\x02 \x03(\v2\x14.cluster.NodeMetricsR\x05nodes\"\xc4\x01\n" +
	"\vNodeMetrics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\fdisk_percent\x18\x04 \x01(\x01R\vdiskPercent\x126\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x16.cluster.NodeConditionR\n" +
	"conditions\";\n" +
	"\rNodeCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"n\n" +
	"\x11PodStatusSnapshot\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.common.EventMetadataR\bmetadata\x12&\n" +
	"\x04pods\x18\x02 \x03(\v2\x12.cluster.PodStatusR\x04pods\"\x81\x01\n" +
	"\tPodStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12#\n" +
	"\rrestart_count\x18\x03 \x01(\x05R\frestartCount\x12\x1d\n" +
	"\n" +
	"oom_killed\x18\x04 \x01(\bR\toomKilledB'Z%eddisonso.com/edd-cloud/proto/clusterb\x06proto3"

var (
	file_cluster_events_proto_rawDescOnce sync.Once
	file_cluster_events_proto_rawDescData []byte
)

func file_cluster_events_proto_rawDescGZIP() []byte {
	file_cluster_events_proto_rawDescOnce.Do(func() {
		file_cluster_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_events_proto_rawDesc), len(file_cluster_events_proto_rawDesc)))
	})
	return file_cluster_events_proto_rawDescData
}

var file_cluster_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cluster_events_proto_goTypes = []any{
	(*ClusterMetrics)(nil),       // 0: cluster.ClusterMetrics
	(*NodeMetrics)(nil),          // 1: cluster.NodeMetrics
	(*NodeCondition)(nil),        // 2: cluster.NodeCondition
	(*PodStatusSnapshot)(nil),    // 3: cluster.PodStatusSnapshot
	(*PodStatus)(nil),            // 4: cluster.PodStatus
	(*common.EventMetadata)(nil), // 5: common.EventMetadata
}
var file_cluster_events_proto_depIdxs = []int32{
	5, // 0: cluster.ClusterMetrics.metadata:type_name -> common.EventMetadata
	1, // 1: cluster.ClusterMetrics.nodes:type_name -> cluster.NodeMetrics
	2, // 2: cluster.NodeMetrics.conditions:type_name -> cluster.NodeCondition
	5, // 3: cluster.PodStatusSnapshot.metadata:type_name -> common.EventMetadata
	4, // 4: cluster.PodStatusSnapshot.pods:type_name -> cluster.PodStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cluster_events_proto_init() }
func file_cluster_events_proto_init() {
	if File_cluster_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_events_proto_rawDesc), len(file_cluster_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_events_proto_goTypes,
		DependencyIndexes: file_cluster_events_proto_depIdxs,
		MessageInfos:      file_cluster_events_proto_msgTypes,
	}.Build()
	File_cluster_events_proto = out.File
	file_cluster_events_proto_goTypes = nil
	file_cluster_events_proto_depIdxs = nil
}
