// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: notification/events.proto

package notification

import (
	common "eddisonso.com/notification-service/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.EventMetadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Target user (nanoid)
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`                 // Short title (e.g., "Container Ready")
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`             // Body text (e.g., "Container 'dev-box' is now running")
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`                   // URL path to navigate to (e.g., "/compute/containers/abc")
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`           // "compute", "storage", "auth", etc.
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`                 // Optional scope within category (e.g., storage namespace name)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_events_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetMetadata() *common.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Notification) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Notification) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

var File_notification_events_proto protoreflect.FileDescriptor

const file_notification_events_proto_rawDesc = "" +
	"\n" +
	"\x19notification/events.proto\x12\fnotification\x1a\x12common/types.proto\"\xd0\x01\n" +
	"\fNotification\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.common.EventMetadataR\bmetadata\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scopeB,Z*eddisonso.com/edd-cloud/proto/notificationb\x06proto3"

var (
	file_notification_events_proto_rawDescOnce sync.Once
	file_notification_events_proto_rawDescData []byte
)

func file_notification_events_proto_rawDescGZIP() []byte {
	file_notification_events_proto_rawDescOnce.Do(func() {
		file_notification_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_events_proto_rawDesc), len(file_notification_events_proto_rawDesc)))
	})
	return file_notification_events_proto_rawDescData
}

var file_notification_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_events_proto_goTypes = []any{
	(*Notification)(nil),         // 0: notification.Notification
	(*common.EventMetadata)(nil), // 1: common.EventMetadata
}
var file_notification_events_proto_depIdxs = []int32{
	1, // 0: notification.Notification.metadata:type_name -> common.EventMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notification_events_proto_init() }
func file_notification_events_proto_init() {
	if File_notification_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_events_proto_rawDesc), len(file_notification_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_events_proto_goTypes,
		DependencyIndexes: file_notification_events_proto_depIdxs,
		MessageInfos:      file_notification_events_proto_msgTypes,
	}.Build()
	File_notification_events_proto = out.File
	file_notification_events_proto_goTypes = nil
	file_notification_events_proto_depIdxs = nil
}
