// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: log/events.proto

package log

import (
	common "eddisonso.com/alerting-service/pkg/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *common.EventMetadata  `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogError) Reset() {
	*x = LogError{}
	mi := &file_log_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogError) ProtoMessage() {}

func (x *LogError) ProtoReflect() protoreflect.Message {
	mi := &file_log_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogError.ProtoReflect.Descriptor instead.
func (*LogError) Descriptor() ([]byte, []int) {
	return file_log_events_proto_rawDescGZIP(), []int{0}
}

func (x *LogError) GetMetadata() *common.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LogError) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogError) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_log_events_proto protoreflect.FileDescriptor

const file_log_events_proto_rawDesc = "" +
	"\n" +
	"\x10log/events.proto\x12\x03log\x1a\x12common/types.proto\"\x85\x01\n" +
	"\bLogError\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.common.EventMetadataR\bmetadata\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05levelB#Z!eddisonso.com/edd-cloud/proto/logb\x06proto3"

var (
	file_log_events_proto_rawDescOnce sync.Once
	file_log_events_proto_rawDescData []byte
)

func file_log_events_proto_rawDescGZIP() []byte {
	file_log_events_proto_rawDescOnce.Do(func() {
		file_log_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_events_proto_rawDesc), len(file_log_events_proto_rawDesc)))
	})
	return file_log_events_proto_rawDescData
}

var file_log_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_log_events_proto_goTypes = []any{
	(*LogError)(nil),             // 0: log.LogError
	(*common.EventMetadata)(nil), // 1: common.EventMetadata
}
var file_log_events_proto_depIdxs = []int32{
	1, // 0: log.LogError.metadata:type_name -> common.EventMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_log_events_proto_init() }
func file_log_events_proto_init() {
	if File_log_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_events_proto_rawDesc), len(file_log_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_events_proto_goTypes,
		DependencyIndexes: file_log_events_proto_depIdxs,
		MessageInfos:      file_log_events_proto_msgTypes,
	}.Build()
	File_log_events_proto = out.File
	file_log_events_proto_goTypes = nil
	file_log_events_proto_depIdxs = nil
}
